project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Data Analysis Portfolio"
  description: "私の分析プロジェクト集"
  repo-url: https://github.com/mizulo-olmizu/quarto_githubpages_sample
  repo-actions: [source]
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo # 清潔感のあるテーマ
    toc: true # 目次を表示
    number-sections: true
    code-fold: true # コードを折りたたみ可能にする
